server:
  servlet:
    contextPath: /inventory
  #port: 0
  port: 9092

spring:
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    generate-ddl: true
  datasource:
    name: inventorydb
  boot:
    admin:
      client:
        url: http://localhost:7777/admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring.main.allow-bean-definition-overriding: true
spring.zipkin.base-url: http://localhost:9411/